name: build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]  # macos-11, ubuntu-20.04, windows-2022
        python-version: ['3.8', '3.9', '3.10']
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Before install
      run: |
        python -m pip install --upgrade pip
        pip install coverage flake8 pytest wheel
    - name: Unix-like Install
      run: |
        python setup.py bdist_wheel
        pip install dist/*.whl
      if: runner.os != 'Windows'
    - name: Windows Install
      run: |
        pip install .
      if: runner.os == 'Windows'
    - name: Lint with flake8
      run: |
        flake8 . --count
    - name: Test with pytest and generate coverage report
      run: |
        coverage run -m pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
